<a href="https://colab.research.google.com/github/piaseckazaneta/Python/blob/main/Mapa_schronisk_dla_psow_BINGO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install folium pandas openpyxl plotly

Requirement already satisfied: folium in /usr/local/lib/python3.12/dist-packages (0.20.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from folium) (2.32.4)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.12/dist-packages (from folium) (2026.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->folium) (2026.2.25)

In [7]:
from google.colab import files
uploaded = files.upload()

Saving schroniska_polska_geo.xlsx to schroniska_polska_geo (1).xlsx
Saving schroniska_statystyki_geo.xlsx to schroniska_statystyki_geo (1).xlsx

In [8]:
import pandas as pd
df_stats = pd.read_excel("schroniska_statystyki_geo.xlsx", sheet_name="statystyki")
df_adopsiaki = pd.read_excel("schroniska_statystyki_geo.xlsx", sheet_name="lokalizacje_adopsiaki")
df_firmy = pd.read_excel("schroniska_statystyki_geo.xlsx", sheet_name="lokalizacje_warsztatow_firmy")
df_schroniska = pd.read_excel("schroniska_polska_geo.xlsx", sheet_name="Schroniska w Polsce")

In [9]:
df_stats.head()

,rok,zgloszenia_adopsiaki,rodziny_adopsiaki,dzieci_warsztaty,placowki_warsztaty,firmy_dfc,wolontariusze,linkedin,facebook,instagram,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,2023,59,11,2726,44,5,7,1214,1242,1279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,2024,77,45,2835,35,9,12,1834,1537,1630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2025,126,63,4846,62,14,16,2140,1976,1891,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,2026,30,3,385,5,2,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rok                     4 non-null      int64
 1    zgloszenia_adopsiaki   4 non-null      int64
 2    rodziny_adopsiaki      4 non-null      int64
 3   dzieci_warsztaty        4 non-null      int64
 4    placowki_warsztaty     4 non-null      int64
 5    firmy_dfc              4 non-null      int64
 6   wolontariusze           4 non-null      int64
 7    linkedin               4 non-null      int64
 8    facebook               4 non-null      int64
 9    instagram              4 non-null      int64
 10   liczba_darczyncow      4 non-null      int64
 11  dane_czesciowe          4 non-null      int64
 12  Unnamed: 12             0 non-null      float64
 13  Unnamed: 13             0 non-null      float64
 14  Unnamed: 14             0 non-null      float64
 15  Unnamed: 15             0 non-null      float64
 16  Unnamed: 16             0 non-null      float64
 17  Unnamed: 17             0 non-null      float64
 18  Unnamed: 18             0 non-null      float64
 19  Unnamed: 19             0 non-null      float64
 20  Unnamed: 20             0 non-null      float64
 21  Unnamed: 21             0 non-null      float64
 22  Unnamed: 22             3 non-null      float64
dtypes: float64(11), int64(12)
memory usage: 868.0 bytes

In [11]:
df_adopsiaki.head()

     miasto  rok_od  X (EPSG:2180)  Y (EPSG:2180)  Lon (WGS84)  Lat (WGS84)
0  Warszawa    2023      641394.81      487279.09    21.071149    52.233374
1      Łódź    2023      533004.32      434158.44    19.478486    51.772824
2  Brzeziny    2023      484051.23      397610.45    19.762611    51.800194
3   Wrocław    2023      358565.05      364114.54    16.978196    51.126311
4    Gdańsk    2025      477517.91      720521.53    18.654023    54.348291

In [12]:
df_firmy.head()

     miasto   rok  X (EPSG:2180)  Y (EPSG:2180)  Lon (WGS84)  Lat (WGS84)
0      Łódź  2025      533004.32      434158.44    19.478486    51.772824
1  Warszawa  2025      641394.81      487279.09    21.071149    52.233374
2   Wrocław  2025      358565.05      364114.54    16.978196    51.126311
3     Opole  2025      424416.70      312967.60    17.929884    50.678793
4  Szczecin  2025      204574.42      627569.52    14.550962    53.430182

In [13]:
df_schroniska.head()

,Lp.,Nazwa schroniska,Miasto,Ulica / adres,Kod pocztowy,Miejscowość,Województwo,Telefon,E-mail,Strona WWW,X (EPSG:2180),Y (EPSG:2180),Lon (WGS84),Lat (WGS84)
0,1,Schronisko dla zwierząt Ciapkowo,Gdynia,ul. Małokacka 3A,81-654,Gdynia,pomorskie,58-622-25-52,schronisko@ciapkowo.pl,http://ciapkowo.pl/,474378.61,740009.05,18.604028,54.523330
1,2,Schronisko dla zwierząt w Tczewie,Tczew,ul. Malinowska,83-110,Tczew,pomorskie,058 531 96 56,tczew@otoz.pl,www.schroniskotczew.pl,485480.39,691856.65,18.777943,54.090876
2,3,OTOZ ANIMALS Schronisko w Dąbrówce k. Wejherowa,Luzino,Dąbrówka Młyn 30,84-242,Luzino,pomorskie,607-540-557,dabrowka@otoz.pl,www.schroniskodabrowka.pl,446531.71,745072.06,18.172778,54.566667
3,4,Schronisko dla zwierząt w Starogardzie Gd.,Starogard Gdański,ul. Hermanowska 24,83-200,Starogard Gdański,pomorskie,058 56 099 31,schroniskostarogard@otoz.pl,http://www.schroniskostarogard.pl,468907.10,679288.20,18.525774,53.977148
4,5,Schronisko dla zwierząt w Elblągu,Elbląg,ul. Królewiecka 233,82-300,Elbląg,warmińsko-mazurskie,055 2341646,elblag.schronisko@otoz.pl,www.schronisko.elblag.pl,528766.24,703939.10,19.441086,54.198900

BUDOWANIE MAPY

 1. Inicjalizacja mapy

In [14]:
import folium

mapa = folium.Map(
    location=[52.0, 19.5],
    zoom_start=6,
    tiles="OpenStreetMap"
)

mapa