<a href="https://colab.research.google.com/github/piaseckazaneta/Python/blob/main/Mini_projekt_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WSTĘP

Tutaj umieścić opis projektu, źródła danych i cel projektu

1. IMPORT BIBLIOTEK

In [1]:
import pandas as pd

from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

2. WCZYTANIE DANYCH

In [2]:
# Ścieżki do dysku google
storm_events_details = "/content/drive/MyDrive/Projekt_Python_2026/StormEvents_details_2025.csv"
storm_events_locations = "/content/drive/MyDrive/Projekt_Python_2026/StormEvents_locations_2025.csv"
storm_events_fatalities = "/content/drive/MyDrive/Projekt_Python_2026/StormEvents_fatalities_2025.csv"

# Wczytanie danych
df_details = pd.read_csv(storm_events_details)
df_locations = pd.read_csv(storm_events_locations)
df_fatalities = pd.read_csv(storm_events_fatalities)

3. PRZEGLĄD DANYCH

Analiza wzrokowa danych

In [3]:
df_details.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,202503,31,1104,202503,31,1106,201366,1252415,GEORGIA,13,...,2.22,W,TYUS,33.4757,-85.238,33.4757,-85.238,A cold-front initiated a line of thunderstorms...,Tree down at the intersection of highway 5 and...,CSV
1,202503,30,1552,202503,30,1555,200337,1241136,MICHIGAN,26,...,1.47,NNE,EDWARDSBURG,41.7900,-86.100,41.8200,-86.070,A cold front pushed into the area during the a...,A brief EF-1 tornado was confirmed in Edwardsb...,CSV
2,202501,5,1800,202501,6,2227,197733,1222851,VIRGINIA,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An area of low pressure tracked across souther...,NaN,CSV
3,202501,3,1300,202501,3,1900,197761,1223112,MARYLAND,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An area of low pressure moved off into New Eng...,NaN,CSV
4,202501,3,1300,202501,3,1900,197761,1223113,MARYLAND,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An area of low pressure moved off into New Eng...,NaN,CSV

In [4]:
df_fatalities.head()

,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,202512,4,0,60389,1296292,I,12/04/2025 00:00:00,40.0,M,Vehicle/Towed Trailer
1,202512,1,0,60391,1296789,I,12/01/2025 00:00:00,35.0,F,Boating
2,202512,3,0,60393,1297305,D,12/03/2025 00:00:00,32.0,M,In Water
3,202512,25,0,60553,1298352,I,12/25/2025 00:00:00,75.0,F,Vehicle/Towed Trailer
4,202512,26,0,60562,1298509,D,12/26/2025 00:00:00,44.0,M,In Water

In [5]:
df_locations.head()

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,202508,204641,1287936,2,3.54,SSE,SINKING COVE,35.0015,-85.9601,3590,8557606
1,202508,203789,1269348,1,2.90,E,BLEASES XRDS,34.0440,-81.7699,342640,8146194
2,202508,203789,1269349,1,0.80,WSW,DOUGLAS,34.6637,-80.8118,3439822,8048708
3,202508,204597,1288676,4,1.45,WSW,HUNTSVILLE,34.7237,-86.6444,3443422,8638664
4,202508,204597,1288677,1,1.79,NW,FT PAYNE ISBELL ARPT,34.4900,-85.7400,3429400,8544400

Wyświetlenie wszystkich atrybutów każdej tabeli

In [6]:
df_details.columns.to_list()

['BEGIN_YEARMONTH',
 'BEGIN_DAY',
 'BEGIN_TIME',
 'END_YEARMONTH',
 'END_DAY',
 'END_TIME',
 'EPISODE_ID',
 'EVENT_ID',
 'STATE',
 'STATE_FIPS',
 'YEAR',
 'MONTH_NAME',
 'EVENT_TYPE',
 'CZ_TYPE',
 'CZ_FIPS',
 'CZ_NAME',
 'WFO',
 'BEGIN_DATE_TIME',
 'CZ_TIMEZONE',
 'END_DATE_TIME',
 'INJURIES_DIRECT',
 'INJURIES_INDIRECT',
 'DEATHS_DIRECT',
 'DEATHS_INDIRECT',
 'DAMAGE_PROPERTY',
 'DAMAGE_CROPS',
 'SOURCE',
 'MAGNITUDE',
 'MAGNITUDE_TYPE',
 'FLOOD_CAUSE',
 'CATEGORY',
 'TOR_F_SCALE',
 'TOR_LENGTH',
 'TOR_WIDTH',
 'TOR_OTHER_WFO',
 'TOR_OTHER_CZ_STATE',
 'TOR_OTHER_CZ_FIPS',
 'TOR_OTHER_CZ_NAME',
 'BEGIN_RANGE',
 'BEGIN_AZIMUTH',
 'BEGIN_LOCATION',
 'END_RANGE',
 'END_AZIMUTH',
 'END_LOCATION',
 'BEGIN_LAT',
 'BEGIN_LON',
 'END_LAT',
 'END_LON',
 'EPISODE_NARRATIVE',
 'EVENT_NARRATIVE',
 'DATA_SOURCE']

In [7]:
df_fatalities.columns.to_list()

['FAT_YEARMONTH',
 'FAT_DAY',
 'FAT_TIME',
 'FATALITY_ID',
 'EVENT_ID',
 'FATALITY_TYPE',
 'FATALITY_DATE',
 'FATALITY_AGE',
 'FATALITY_SEX',
 'FATALITY_LOCATION']

In [8]:
df_locations.columns.to_list()

['YEARMONTH',
 'EPISODE_ID',
 'EVENT_ID',
 'LOCATION_INDEX',
 'RANGE',
 'AZIMUTH',
 'LOCATION',
 'LATITUDE',
 'LONGITUDE',
 'LAT2',
 'LON2']

Sprawdzenie rozmiarów tabel i typów kolumn

In [9]:
df_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72241 entries, 0 to 72240
Data columns (total 51 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   BEGIN_YEARMONTH     72241 non-null  int64
 1   BEGIN_DAY           72241 non-null  int64
 2   BEGIN_TIME          72241 non-null  int64
 3   END_YEARMONTH       72241 non-null  int64
 4   END_DAY             72241 non-null  int64
 5   END_TIME            72241 non-null  int64
 6   EPISODE_ID          72241 non-null  int64
 7   EVENT_ID            72241 non-null  int64
 8   STATE               72241 non-null  object
 9   STATE_FIPS          72241 non-null  int64
 10  YEAR                72241 non-null  int64
 11  MONTH_NAME          72241 non-null  object
 12  EVENT_TYPE          72241 non-null  object
 13  CZ_TYPE             72241 non-null  object
 14  CZ_FIPS             72241 non-null  int64
 15  CZ_NAME             72241 non-null  object
 16  WFO                 72241 non-null  object
 17  BEGIN_DATE_TIME     72241 non-null  object
 18  CZ_TIMEZONE         72241 non-null  object
 19  END_DATE_TIME       72241 non-null  object
 20  INJURIES_DIRECT     72241 non-null  int64
 21  INJURIES_INDIRECT   72241 non-null  int64
 22  DEATHS_DIRECT       72241 non-null  int64
 23  DEATHS_INDIRECT     72241 non-null  int64
 24  DAMAGE_PROPERTY     55842 non-null  object
 25  DAMAGE_CROPS        55095 non-null  object
 26  SOURCE              72241 non-null  object
 27  MAGNITUDE           38971 non-null  float64
 28  MAGNITUDE_TYPE      29741 non-null  object
 29  FLOOD_CAUSE         7817 non-null   object
 30  CATEGORY            0 non-null      float64
 31  TOR_F_SCALE         1591 non-null   object
 32  TOR_LENGTH          1591 non-null   float64
 33  TOR_WIDTH           1591 non-null   float64
 34  TOR_OTHER_WFO       282 non-null    object
 35  TOR_OTHER_CZ_STATE  282 non-null    object
 36  TOR_OTHER_CZ_FIPS   282 non-null    float64
 37  TOR_OTHER_CZ_NAME   282 non-null    object
 38  BEGIN_RANGE         43917 non-null  float64
 39  BEGIN_AZIMUTH       43917 non-null  object
 40  BEGIN_LOCATION      43917 non-null  object
 41  END_RANGE           43917 non-null  float64
 42  END_AZIMUTH         43917 non-null  object
 43  END_LOCATION        43917 non-null  object
 44  BEGIN_LAT           43917 non-null  float64
 45  BEGIN_LON           43917 non-null  float64
 46  END_LAT             43917 non-null  float64
 47  END_LON             43917 non-null  float64
 48  EPISODE_NARRATIVE   72241 non-null  object
 49  EVENT_NARRATIVE     61496 non-null  object
 50  DATA_SOURCE         72241 non-null  object
dtypes: float64(11), int64(15), object(25)
memory usage: 28.1+ MB

In [10]:
df_details.shape

(72241, 51)

In [11]:
df_fatalities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FAT_YEARMONTH      895 non-null    int64
 1   FAT_DAY            895 non-null    int64
 2   FAT_TIME           895 non-null    int64
 3   FATALITY_ID        895 non-null    int64
 4   EVENT_ID           895 non-null    int64
 5   FATALITY_TYPE      895 non-null    object
 6   FATALITY_DATE      895 non-null    object
 7   FATALITY_AGE       743 non-null    float64
 8   FATALITY_SEX       785 non-null    object
 9   FATALITY_LOCATION  895 non-null    object
dtypes: float64(1), int64(5), object(4)
memory usage: 70.1+ KB

In [12]:
df_fatalities.shape

(895, 10)

In [13]:
df_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51870 entries, 0 to 51869
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   YEARMONTH       51870 non-null  int64
 1   EPISODE_ID      51870 non-null  int64
 2   EVENT_ID        51870 non-null  int64
 3   LOCATION_INDEX  51870 non-null  int64
 4   RANGE           51870 non-null  float64
 5   AZIMUTH         51870 non-null  object
 6   LOCATION        51870 non-null  object
 7   LATITUDE        51870 non-null  float64
 8   LONGITUDE       51870 non-null  float64
 9   LAT2            51870 non-null  int64
 10  LON2            51870 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 4.4+ MB

In [14]:
df_locations.shape

(51870, 11)

Sprawdzenie braków w danych

In [15]:
df_details.isnull().sum()

BEGIN_YEARMONTH           0
BEGIN_DAY                 0
BEGIN_TIME                0
END_YEARMONTH             0
END_DAY                   0
END_TIME                  0
EPISODE_ID                0
EVENT_ID                  0
STATE                     0
STATE_FIPS                0
YEAR                      0
MONTH_NAME                0
EVENT_TYPE                0
CZ_TYPE                   0
CZ_FIPS                   0
CZ_NAME                   0
WFO                       0
BEGIN_DATE_TIME           0
CZ_TIMEZONE               0
END_DATE_TIME             0
INJURIES_DIRECT           0
INJURIES_INDIRECT         0
DEATHS_DIRECT             0
DEATHS_INDIRECT           0
DAMAGE_PROPERTY       16399
DAMAGE_CROPS          17146
SOURCE                    0
MAGNITUDE             33270
MAGNITUDE_TYPE        42500
FLOOD_CAUSE           64424
CATEGORY              72241
TOR_F_SCALE           70650
TOR_LENGTH            70650
TOR_WIDTH             70650
TOR_OTHER_WFO         71959
TOR_OTHER_CZ_STATE    71959
TOR_OTHER_CZ_FIPS     71959
TOR_OTHER_CZ_NAME     71959
BEGIN_RANGE           28324
BEGIN_AZIMUTH         28324
BEGIN_LOCATION        28324
END_RANGE             28324
END_AZIMUTH           28324
END_LOCATION          28324
BEGIN_LAT             28324
BEGIN_LON             28324
END_LAT               28324
END_LON               28324
EPISODE_NARRATIVE         0
EVENT_NARRATIVE       10745
DATA_SOURCE               0
dtype: int64

In [16]:
df_fatalities.isnull().sum()

FAT_YEARMONTH          0
FAT_DAY                0
FAT_TIME               0
FATALITY_ID            0
EVENT_ID               0
FATALITY_TYPE          0
FATALITY_DATE          0
FATALITY_AGE         152
FATALITY_SEX         110
FATALITY_LOCATION      0
dtype: int64

In [17]:
df_locations.isnull().sum()

YEARMONTH         0
EPISODE_ID        0
EVENT_ID          0
LOCATION_INDEX    0
RANGE             0
AZIMUTH           0
LOCATION          0
LATITUDE          0
LONGITUDE         0
LAT2              0
LON2              0
dtype: int64

Sprawdzenie pełnej listy zjawisk, jakie wystąpiły.

In [18]:
df_details['EVENT_TYPE'].unique()

array(['Thunderstorm Wind', 'Tornado', 'Winter Storm', 'Winter Weather',
       'High Wind', 'Extreme Cold/Wind Chill', 'Hail', 'Flash Flood',
       'Blizzard', 'Strong Wind', 'Heavy Snow', 'Flood',
       'Marine High Wind', 'Excessive Heat', 'Marine Thunderstorm Wind',
       'Marine Hail', 'Frost/Freeze', 'Sneakerwave', 'Drought',
       'Funnel Cloud', 'Heavy Rain', 'Heat', 'Wildfire', 'Dust Storm',
       'Debris Flow', 'Cold/Wind Chill', 'Rip Current', 'Waterspout',
       'Coastal Flood', 'Lightning', 'Avalanche', 'High Surf',
       'Lake-Effect Snow', 'Dense Fog', 'Ice Storm', 'Sleet',
       'Astronomical Low Tide', 'Marine Strong Wind', 'Freezing Fog',
       'Marine Dense Fog', 'Marine Tropical Storm', 'Tropical Storm',
       'Tsunami', 'Seiche', 'Tropical Depression', 'Storm Surge/Tide',
       'Lakeshore Flood', 'Dust Devil'], dtype=object)

SELEKCJA ATRYBUTÓW

Zmiana nazw kolumn w df-ach na małe litery

In [19]:
df_details.columns = df_details.columns.str.lower()
df_fatalities.columns = df_fatalities.columns.str.lower()
df_locations.columns = df_locations.columns.str.lower()

Selekcja zmiennych do analiz

In [23]:
df_details_analysis = df_details[["event_id", "state", "event_type", "begin_date_time", "damage_property", "damage_crops", "tor_f_scale", "tor_length", "tor_width"]]

In [24]:
df_fatalities_analysis = df_fatalities[["event_id", "fatality_age", "fatality_sex", "fatality_location"]]

In [26]:
df_locations_analysis = df_locations[["event_id", "latitude", "longitude"]]